global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: slack-notifications

receivers:
  - name: slack-notifications
    slack_configs:
      - send_resolved: true
        text: '{{ .CommonAnnotations.summary }} - {{ .CommonAnnotations.description }}'
        api_url: 'https://hooks.slack.com/services/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'  
