apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1     
      maxSurge: 1   
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-app
        image: aditya929/todo-app:v4
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_HOST
          value: "mongo-service"
        - name: MONGO_PORT
          value: "27017"
        livenessProbe:
          httpGet:
            path: /health        
            port: 8000
          initialDelaySeconds: 15   
          periodSeconds: 10          
          failureThreshold: 5    
        readinessProbe:
          httpGet:
            path: /ready           
            port: 8000
          initialDelaySeconds: 15     
          periodSeconds: 5            
          failureThreshold: 5  

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
